### ISSUE TITLE
Please complete homework, you are missing a whole section

### ISSUE THREAD

**Issue by philmcneely** [maharris73/V4Q#1]
please follow these steps:
http://apps.bridge360.io:32901/display/CLASS12/Working+with+GitHub+repositories#WorkingwithGitHubrepositories-ProcessforCloninganexistingrepository:

**Comment by maharris73** [comment]
Complete

**Comment by philmcneely** [comment]
this part is missing still

**Comment by maharris73** [comment]
Done
