### ISSUE TITLE
Please delete template.txt from V4Q/Class11/TestTools1_Prework/ directory

### ISSUE THREAD

**Issue by philmcneely** [maharris73/V4Q#2]
Please delete. While it probably wasnt 100% clear that it should be removed, renaming it shoudl have taken care of it.  It appears you copied and renamed instead, which is fine, but then you forgot to delete the original.

**Comment by maharris73** [comment]
Complete

**Comment by philmcneely** [comment]
Still listed, so maybe you missed a push?

**Comment by maharris73** [comment]
I found what the issue was. Complete
